FROM nodered/node-red-docker

MAINTAINER "youhei"

# system update

# web server install

#ADD hello.html /var/www/html

RUN npm install node-red-dashboard
#RUN npm install node-red-contrib-oracledb
RUN npm install node-red-contrib-azure-iot-hub
RUN npm install node-red-contrib-azure-sql
RUN npm install node-red-node-sqlite
RUN npm install node-red-node-emoncms
#RUN npm install node-red-contrib-spreadsheet-in
#RUN npm install node-red-node-email
#RUN npm install node-red-node-twitter
#RUN npm install node-red-node-random
RUN npm install node-red-node-smooth
RUN npm install node-red-contrib-browser-utils
#RUN npm install node-red-contrib-mqtt-broker

RUN npm install node-red-contrib-cognitive-services 
#RUN npm install node-red-contrib-azure-sql 
#RUN npm install node-red-contrib-azure-iot-hub
RUN npm install node-red-contrib-azure-blob-storage 
RUN npm install node-red-contrib-azure-table-storage
RUN npm install node-red-contrib-azureiothubnode 
RUN npm install node-red-contrib-azure-https 
RUN npm install node-red-contrib-azure-documentdb





